Vetka
ZebanNikolay/StudyCycles pull request #2
Opened 2020-07-12 20:20 UTC by Kislatron

kak to tak.

2020-07-13 06:37 UTC, ZebanNikolay commented
Заканчивай с веселыми коментариями и названиями Gotovo, Vetka. Учись называть правильно, описывая что ты делал.
Каждое задание выполняй в новой ветке, а не в старой.

2020-07-13 06:39 UTC, ZebanNikolay commented
Незабывая мержить мой мастер в свой мастер

2020-07-13 06:54 UTC, ZebanNikolay requested changes

2020-07-13 06:54 UTC, ZebanNikolay commented on app/build.gradle
>      implementation 'androidx.appcompat:appcompat:1.1.0'
Расскажи зачем тебе вот это implementation fileTree(dir: 'libs', include: ['*.jar'])

2020-07-13 06:54 UTC, ZebanNikolay commented on app/build.gradle
>      implementation 'androidx.appcompat:appcompat:1.1.0'
Не поднял kotlin_version

2020-07-13 06:54 UTC, ZebanNikolay commented on app/build.gradle
>      implementation 'androidx.appcompat:appcompat:1.1.0'
Вот это забыл testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

2020-07-13 19:22 UTC, Kislatron commented on app/build.gradle
>      implementation 'androidx.appcompat:appcompat:1.1.0'
Тоже удалить его нужно? Я просто трогал, толко то, что в Dependencies.

2020-07-13 19:38 UTC, Kislatron commented on app/build.gradle
>      implementation 'androidx.appcompat:appcompat:1.1.0'
ext.kotlin_version = '1.3.71' , разве это не последняя стабильная версия?

2020-07-13 20:57 UTC, Kislatron commented on app/build.gradle
>      implementation 'androidx.appcompat:appcompat:1.1.0'
Ну я это не добавлял, это изначально было. Погуглил что это такое, это нужно для чтения локальных библиотек.

2020-07-14 07:52 UTC, ZebanNikolay commented on app/build.gradle
>      implementation 'androidx.appcompat:appcompat:1.1.0'
![image](https://user-images.githubusercontent.com/11868794/87399465-11b9bf80-c5c0-11ea-890b-50c81f964745.png)

2020-07-14 07:52 UTC, ZebanNikolay commented on app/build.gradle
>      implementation 'androidx.appcompat:appcompat:1.1.0'
да, нужно

2020-07-14 07:54 UTC, ZebanNikolay commented on app/build.gradle
>      implementation 'androidx.appcompat:appcompat:1.1.0'
Ну я тут намекал, что прочитай и удали, так как у тебя нету локальных библиотек)

2020-07-14 15:57 UTC, Kislatron commented on app/build.gradle
>      implementation 'androidx.appcompat:appcompat:1.1.0'
удалил.

2020-07-14 16:38 UTC, closed without merging