Feature3
ZebanNikolay/StudyCycles pull request #4
Opened 2020-07-21 20:41 UTC by Kislatron

Updates:
- Material component button added
- Transion between activities through Fabric Method

2020-07-22 11:18 UTC, ZebanNikolay requested changes

2020-07-22 11:18 UTC, ZebanNikolay commented on app/src/main/java/com/example/studycycles/MainActivity.kt
>      }
Не забывай нажимать ctrl + alt + L а то у тебя форматирование поехало

2020-07-22 11:18 UTC, ZebanNikolay commented on app/src/main/java/com/example/studycycles/TimerActivity.kt
> +        fun startActivity(btnStart: FragmentActivity) {
btnStart название параметра какое то левое, оно должно только обьяснять параметр внутри функции, но не как, что происходит снаружи. Назови просто activity

2020-07-22 11:18 UTC, ZebanNikolay commented on app/src/main/res/layout/activity_main.xml
> +        android:text="@string/Start"
ресурсы называть с маленькой буквы

2020-07-22 11:18 UTC, ZebanNikolay commented on app/src/main/res/layout/activity_main.xml
> +        android:textAppearance="@style/TextAppearance.AppCompat.Body1"
Ставь сразу стиль и материал. android:textAppearance не нужен, так как он в стиле уже будет

2020-07-24 19:32 UTC, Kislatron commented on app/src/main/java/com/example/studycycles/MainActivity.kt
>      }
Listo

2020-07-27 18:06 UTC, closed without merging